import Navbar from '@/components/navbar/Navbar'

import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Footer from '@/sections/footer/Footer'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next Template',
  description: 'Generated by create next template',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className='flex flex-col justify-between ite w-full min-h-screen'>
          {/* <Header /> */}
          <Navbar />
          {children}
          {/* <Footer /> */}
          <Footer />
        </div>
      </body>
    </html>
  )
}
